require("options")
-- plugins
require("config.lazy")
--require("plugins")
require("config.colorscheme")
require("config.formatter")
require("config.filetypes-prelsp")
require("config.lsp")
require("config.treesitter-cfg")
require("config.morefiletypes")
require("config.dapconfig")
require("config.hexedit")
require("commands.user_commands")

require("keymaps")
